Repository suraj-singh12/BashScripts, pull requests merged in 2022-10, with the labels that each got.

#7 Added script `set timerX` (like google's set time X) [countdown timer]
  timerX/install.sh
  timerX/stx.sh
  timerX/usage.md
Labels: hacktoberfest-accepted

#6 Added ip address script
  ip/ip.sh
  ip/readme.txt
Labels: enhancement, hacktoberfest-accepted

#13 add pdf2text to BashScript open source program
  pdf2text/pdf2text.sh
  pdf2text/readme.md
  pdf2text/requirements.sh
Labels: enhancement, hacktoberfest-accepted

#8 Setup your web server(NGINX,FIREWALL,GIT,NODE,YARN)
  Basic Web Server Setup(Ubuntu)/README.md
  Basic Web Server Setup(Ubuntu)/setup.sh
Labels: enhancement, hacktoberfest-accepted

#12 added autostart for apps and firefox with tabs
  launchMultipleAppsAtOnce/Readme.md
  launchMultipleAppsAtOnce/launchMultipleAppsAtOnce.sh
Labels: enhancement, hacktoberfest-accepted

#20 Updated Readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#28 `system-load-live-updates`
  system-load-pretty-live/README.md
  system-load-pretty-live/sysPretty.sh
Labels: hacktoberfest, hacktoberfest-accepted

#32 Create tomonitor.sh
  geolocation/location.sh
  hacks/tomanaged.sh
  hacks/tomonitor.sh
Labels: hacktoberfest, hacktoberfest-accepted

#36 Added the script and ReadMe file for Directory and Os info
  Directory & Os info/README.md
  Directory & Os info/script.sh
Labels: good first issue
